export const company = {
  uuid: '4cb69f69-4a86-48e5-b2b5-654b3e6c297f',
  name: 'Roga Invest Holding',
  logoUrl: null,
  regNumber: '768594523784',
  regNumName: 'OGRN',
  regDocUrl: 'https:fb.com/feed',
  issuingAuthority: 'FHS  No 46',
  // eslint-disable-next-line max-len
  description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus ducimus dolores iure illum explicabo perspiciatis, dolorum ipsa earum. Non eos ex quis autem quod mollitia voluptas ab iure perspiciatis amet! Exercitationem odit pariatur, voluptatum beatae optio, nobis voluptate officia sint aspernatur repudiandae quam dignissimos, dicta velit. Est cumque deleniti hic architecto! Labore ab, aspernatur recusandae doloribus quo cumque dolore suscipit perspiciatis consectetur soluta expedita fugiat ipsam in, ea culpa vitae cum laborum reprehenderit beatae aut quod nostrum ex reiciendis. Fuga incidunt aspernatur, officiis, corrupti vel cum cumque deleniti earum esse culpa quasi excepturi aliquam architecto facere sunt voluptas porro saepe ipsum laborum qui voluptate, officia repellendus perspiciatis magni? Repellat temporibus quidem natus quas voluptas deserunt tempora id odit, dolor dolorem. Alias amet dolorem optio et incidunt, laborum ipsam nam omnis rerum, quo officiis soluta ex explicabo nulla qui eos a facere porro fugit ducimus doloribus. Quas illo sit dolorum expedita? ',
  yearOfFoundation: 1439,
  website: 'https://link.com/',
  ceo: 'Ivanov Ivan Ivanovich',
  ceoDocUrl: 'https:fb.com/feed',
  qcEmployees: 'More 100',
  budgetOfYear: 'From 50 to 100 million rubles',
  currencyOfBudget: 'Rub',
  moderated: null,
  moderatedReason: null,
  addresses: [
    {
      postCode: 178567,
      country: 'Russia',
      city: 'Moscow',
      street: 'Lenina st.',
      buildNum: 'house 67',
      roomNum: 'office 49',
      addressType: 'Actual',
    },
    {
      postCode: 178567,
      country: 'Russia',
      city: 'Omsk',
      street: 'Tylenina st.',
      buildNum: 'house 32',
      roomNum: '54',
      addressType: 'Post',
    },
  ],
  legalForm: 'Partnership',
  bussinesType: 'Diller',
  contacts: [
    {
      name: 'Facebook',
      url: 'https://link.com/',
    },
    {
      name: 'VK',
      url: 'https://link.com/',
    },
    {
      name: 'Twitter',
      url: 'https://link.com/',
    },
  ],
};
