export const mokData = {
  uuid: '4cb69f69-4a86-48e5-b2b5-654b3e6c297f',
  name: 'Roga Invest Holding',
  regNumber: null,
  regNumName: null,
  regDocUrl: 'https:fb.com/feed',
  issuingAuthority: null,
  description: 'Company document No 647443',
  yearOfFoundation: 1439,
  website: 'https://link.com/',
  ceo: 'Ivanov Ivan Ivanovich',
  ceoDocUrl: 'https:fb.com/feed',
  qcEmployees: 'More 100',
  budgetOfYear: 'More 100',
  currencyOfBudget: 'More 100',
  moderated: 'idle',
  moderatedReason: null,
  addresses: [
    {
      postCode: 178567,
      street: 'Lenina st.',
      buildNum: 'house 67',
      roomNum: 'office 49',
      addressType: 'Actual',
    },
  ],
  legalForm: 'Partnership',
  bussinesType: 'Diller',
  contacts: [],
};
