version: '3.0'

services:
  rmhtc_api:
    container_name: rmhtc_api
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./app/node_modules
    ports:
      - 8000:8000
    command: npm run start:local
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=2GB"
      - "-c"
      - "work_mem=64MB"
      - "-c"
      - "maintenance_work_mem=128MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=5GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_DB: rmhtc_local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  client:
    build: ./frontend
    container_name: itc_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - ./app/node_modules
    stdin_open: true
    tty: true

volumes:
  pgdata: