import type { NextPage } from 'next';
import Head from 'next/head';
import { Events } from '../components/Events/Events';
import { Header } from '../components/Header/Header';
import { Headline } from '../components/Headline/Headline';

const Home: NextPage = () => (
  <div>
    <Head>
      <title>RMHTC</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header />
    <Headline />
    <Events />
  </div>
);

export default Home;
