import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { Events } from '../components/Events/Events';
import { Header } from '../components/Header/Header';
import { Headline } from '../components/Headline/Headline';
import { LoginForm } from '../components/LoginForm/LoginForm';
import { Modal } from '../components/Modal/Modal';
import { SignupForm } from '../components/SignupForm/SignupForm';

const Home: NextPage = () => {
  const router = useRouter();
  const isSignUpModal = router.query.modal === 'signup';
  const isLoginModal = router.query.modal === 'login';
  return (
    <div>
      <Head>
        <title>RMHTC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Headline />
      <Events />
      {isSignUpModal && (
        <Modal>
          <SignupForm />
        </Modal>
      )}
      {isLoginModal && (
        <Modal>
          <LoginForm />
        </Modal>
      )}
    </div>
  );
};

export default Home;
