export const USER_REPOSITORY = 'USER_REPOSITORY';
export const ROLE_REPOSITORY = 'ROLE_REPOSITORY';
export const EMAIL_TOKEN_REPOSITORY = 'EMAIL_TOKEN_REPOSITORY';
export const REFRESH_TOKEN_REPOSITORY = 'REFRESH_TOKEN_REPOSITORY';
export const COMPANY_REPOSITORY = 'COMPANY_REPOSITORY';
export const ADDRESS_REPOSITORY = 'ADDRESS_REPOSITORY';
export const ADDRESS_TYPE_REPOSITORY = 'ADDRESS_TYPE_REPOSITORY';
export const COUNTRY_REPOSITORY = 'COUNTRY_REPOSITORY';
export const CITY_REPOSITORY = 'CITY_REPOSITORY';
export const MESSENGER_REPOSITORY = 'MESSENGER_REPOSITORY';
export const MESSENGER_TYPE_REPOSITORY = 'MESSENGER_TYPE_REPOSITORY';
export const BUSINESS_TYPE_REPOSITORY = 'BUSINESS_TYPE_REPOSITORY';
export const LEGAL_FORM_REPOSITORY = 'LEGAL_FORM_REPOSITORY';
export const CONTACT_TYPE_REPOSITORY = 'CONTACT_TYPE_REPOSITORY';
export const CONTACT_REPOSITORY = 'CONTACT_REPOSITORY';

export const JWT_AUTH_GUARD = 'JWT_AUTH_DUARD';
