import { NextPage } from 'next';
import Head from 'next/head';
import styles from './CompanyPage.module.css';
import { CompanyCard } from '../../../../components/CompanyCard/CompanyCard';
import { Footer } from '../../../../components/Footer/Footer';
import { Header } from '../../../../components/Header/Header';

const CompanyPage: NextPage = () => (
  <div className={styles.page}>
    <Head>
      <title>ITC</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header middle="navMenu" />
    <main className={styles.content}>
      <CompanyCard access="general" />
    </main>
    <Footer />
  </div>
);
export default CompanyPage;
