/* eslint-disable react-hooks/exhaustive-deps */
import { NextPage } from 'next';
import { useForm } from 'react-hook-form';
import Head from 'next/head';
import styles from '../CatalogPage.module.css';
import { Header } from '../../../components/Header/Header';
import { SimpleSearch } from '../../../components/SimpleSearch/SimpleSearch';
import { CheckboxFilter } from '../../../components/CheckboxFilter/CheckboxFilter';
import { Footer } from '../../../components/Footer/Footer';
import {
  country,
} from '../../../mockData/catalogMockData';
import { Button } from '../../../components/Button/Button';
import { NavLink } from '../../../components/NavLink/NavLink';
import { OffersCatalog } from '../../../components/OffersCatalog/OffersCatalog';

type FormData = {
  country?: string[];
};

const CatalogOffersPage: NextPage = () => {
  const { handleSubmit, register } = useForm<FormData>();

  const submitFormHandler = (data: FormData) => {
    console.log(data);
  };

  // const handleGetMore = () => {
  //   if (companiesData && companiesData.count > 9) {
  //     getCompanies(companiesData.page + 1)
  //       .then((res) => setCompaniesData((prevState: any) => ({
  //         ...prevState,
  //         companies: prevState?.companies.concat(res.data.companies),
  //         page: prevState.page + 1,
  //       })));
  //   }
  // };

  return (
    <div className={styles.page}>
      <Head>
        <title>ITC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header middle="navMenu" />
      <main className={styles.content}>
        <div className={styles.content__searchBar}>
          <SimpleSearch />
          <nav>
            <ul className={styles.content__nav}>
              <li>
                <NavLink href="/catalog/companies" className={styles.nav__link} activeClass={styles.nav__link_active}>
                  Companies
                </NavLink>
              </li>
              <li>
                <NavLink href="/catalog/offers" className={styles.nav__link} activeClass={styles.nav__link_active}>
                  Offers
                </NavLink>
              </li>
              <li>
                <NavLink href="/catalog/requests" className={styles.nav__link} activeClass={styles.nav__link_active}>
                  Requests
                </NavLink>
              </li>
            </ul>
          </nav>
        </div>
        <OffersCatalog />
        <form className={styles.content__filtersBar} onSubmit={handleSubmit(submitFormHandler)}>
          <CheckboxFilter filters={country} label="Country" register={register} fieldName="country" />
          <div className={styles.content__filtersControls}>
            <Button className={styles.content__filtersButton} type="reset">Reset</Button>
            <Button className={styles.content__filtersButton} appearance="primary" type="submit">Apply</Button>
          </div>
        </form>
      </main>
      <Footer />
    </div>
  );
};

export default CatalogOffersPage;
