export const mockCompany = {
  uuid: '4cb69f69-4a86-48e5-b2b5-654b3e6c297f',
  name: 'Roga Invest Holding',
  logoUrl: null,
  regNumber: '768594523784',
  regNumName: 'OGRN',
  regDocUrl: 'http://link.com/',
  issuingAuthority: 'FHS  No 46',
  // eslint-disable-next-line max-len
  description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus ducimus dolores iure illum explicabo perspiciatis, dolorum ipsa earum. Non eos ex quis autem quod mollitia voluptas ab iure perspiciatis amet! Exercitationem odit pariatur, voluptatum beatae optio, nobis voluptate officia sint aspernatur repudiandae quam dignissimos, dicta velit. Est cumque deleniti hic architecto! Labore ab, aspernatur recusandae doloribus quo cumque dolore suscipit perspiciatis consectetur soluta expedita fugiat ipsam in, ea culpa vitae cum laborum reprehenderit beatae aut quod nostrum ex.',
  yearOfFoundation: '1439',
  website: 'https:fb.com/feed',
  ceo: 'Ivanov Ivan Ivanovich',
  ceoDocUrl: 'https:fb.com/feed',
  qcEmployees: 'More 100',
  budgetOfYear: 'From 50 to 100 million rubles',
  currencyOfBudget: 'Rub',
  moderated: null,
  moderatedReason: null,
  businessType: 'Reseller',
  createdAt: '2022-09-07T07:25:30.027Z',
  moderatedAuthorUuid: 'b5e60449-ca8e-4d2b-9ec5-50353d22970f',
  shortLegalForm: 'LLC',
  presentationUrl: null,
  addresses: [
    {
      postCode: 178567,
      country: 'Russia',
      city: 'Moscow',
      street: 'Red Square',
      buildNum: 'house 1',
      roomNum: 'office 1',
      addressType: 'Legal',
      uuid: '1',
    },
    {
      postCode: 178567,
      country: 'Russia',
      city: 'St. Petersburg',
      street: 'Lenina st.',
      buildNum: 'house 67',
      roomNum: 'office 49',
      addressType: 'Actual',
      uuid: '2',
    },
    {
      postCode: 178567,
      country: 'Russia',
      city: 'Omsk',
      street: 'Tylenina st.',
      buildNum: 'house 32',
      roomNum: '54',
      addressType: 'Mailing',
      uuid: '3',
    },
  ],
  legalForm: 'Partnership',
  bussinesType: 'Diller',
  messengers: [
    {
      type: 'Telegram',
      value: 'https://t.me/',
      uuid: '1',
    },
    {
      type: 'WhatsApp',
      value: 'https://www.whatsapp.com/',
      uuid: '2',
    },
    {
      type: 'LinkedIn',
      value: 'https://www.linkedin.com/',
      uuid: '3',
    },
    {
      type: 'Facebook',
      value: 'https://m.facebook.com//',
      uuid: '4',
    },
  ],
  contacts: [
    {
      type: 'Work phone',
      value: '8123456789',
      uuid: '1',
    },
    {
      type: 'Mobile phone',
      value: '+71523456789',
      uuid: '2',
    },
    {
      type: 'Fax',
      value: '+71523456789',
      uuid: '3',
    },
    {
      type: 'Email',
      value: 'any.mail@mail.com',
      uuid: '4',
    },
  ],
};
