import { NextPage } from 'next';
import Head from 'next/head';
import styles from './OfferPage.module.css';
import { Footer } from '../../../../components/Footer/Footer';
import { Header } from '../../../../components/Header/Header';
import { OfferCard } from '../../../../components/OfferCard/OfferCard';

const OfferPage: NextPage = () => (
  <div className={styles.page}>
    <Head>
      <title>ITC</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header middle="navMenu" />
    <main className={styles.content}>
      <OfferCard />
    </main>
    <Footer />
  </div>
);
export default OfferPage;
