import { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import styles from './CatalogPage.module.css';
import { Header } from '../../../components/Header/Header';
import { SimpleSearch } from '../../../components/SimpleSearch/SimpleSearch';
import { Filter } from '../../../components/Filter/Filter';
import { Catalog } from '../../../components/Catalog/Catalog';
import { Footer } from '../../../components/Footer/Footer';

const companyType = ['Manufacturer', 'Wholesaler', 'Resaller', 'Dropshipper', 'Trading Company', 'Something', 'Something else'];
const legalForm = [
  'Limited Liability Company', 'Joint-stock company', 'Partnership', 'Internet shop', 'Consumer cooperative', 'Something', 'Something else'];
const annualTurner = ['From 50 million', 'From 50 to 100 million', 'More 100 million'];
const employees = ['Up to 50', 'From 50 to 100', 'More 100'];
const country = ['Russia', 'Malaysia', 'Singapure'];

const CatalogPage: NextPage = () => (
  <div className={styles.page}>
    <Head>
      <title>RMHTC</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header middle="navMenu" />
    <main className={styles.content}>
      <div className={styles.content__searchBar}>
        <SimpleSearch />
        <nav>
          <ul className={styles.content__nav}>
            <li><Link href="/catalog/companies"><a className={`${styles.nav__link} ${styles.nav__link_active}`}>Companies</a></Link></li>
            <li><Link href="/catalog/companies"><a className={styles.nav__link}>Offers</a></Link></li>
            <li><Link href="/catalog/companies"><a className={styles.nav__link}>Requests</a></Link></li>
          </ul>
        </nav>
      </div>
      <div className={styles.content__filtersBar}>
        <Filter filters={companyType} label="Company type" name="companyType" htmlType="checkbox" />
        <Filter filters={legalForm} label="Legal form" name="legalForm" htmlType="checkbox" />
        <Filter filters={annualTurner} label="Annual turner" name="annualTurner" htmlType="checkbox" />
        <Filter filters={employees} label="Total number of employees" name="employees" htmlType="checkbox" />
        <Filter filters={country} label="Country" name="country" htmlType="checkbox" />
      </div>
      <Catalog className={styles.content__catalog} />
    </main>
    <Footer />
  </div>
);

export default CatalogPage;
