import { NextPage } from 'next';
import Head from 'next/head';
import styles from './Catalog.module.css';
import { Header } from '../../../components/Header/Header';

const Catalog: NextPage = () => (
  <div className={styles.page}>
    <Head>
      <title>RMHTC</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header middle="navMenu" />
    <main className={styles.content}>
      <h1>Catalog</h1>
    </main>
    <footer className={styles.footer}><h2>footer</h2></footer>
  </div>
);

export default Catalog;
